name: Build APK

on:
  push:
    branches:
      - main  # Ejecutar solo cuando haya cambios en la rama main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Clonar el repositorio
    - name: Checkout code
      uses: actions/checkout@v2

    # 2. Instalar dependencias de Python (Kivy y Buildozer)
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip build-essential libssl-dev libffi-dev python3-dev
        pip install --upgrade pip
        pip install cython==0.29.21
        pip install buildozer

    # 3. Configurar el entorno de Android
    - name: Install Android SDK and NDK
      run: |
        sudo apt install -y openjdk-8-jdk
        sudo apt-get install -y android-sdk

    # 4. Instalar Buildozer y construir el APK
    - name: Build APK
      run: |
        buildozer android debug

    # 5. Guardar el APK generado como artefacto
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-apk
        path: bin/*.apk